/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author Aryan Kesarwani
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    double first;
    double second;
    double result;
    String Operation;
    String answer;
    
    public Calculator() {
        initComponents();
    }
    @Override
    public void enable(){
        jTextField2.setEnabled(true);
        jRadioButton2.setEnabled(false);
        jRadioButton1.setEnabled(true);
        but1.setEnabled(true);
        but2.setEnabled(true);
        but3.setEnabled(true);
        but4.setEnabled(true);
        but5.setEnabled(true);
        but6.setEnabled(true);
        but7.setEnabled(true);
        but8.setEnabled(true);
        but9.setEnabled(true);
        but10.setEnabled(true);
        but11.setEnabled(true);
        but12.setEnabled(true);
        but13.setEnabled(true);
        but14.setEnabled(true);
        but15.setEnabled(true);
        but16.setEnabled(true);
        but17.setEnabled(true);
        but18.setEnabled(true);
        but19.setEnabled(true);
        but20.setEnabled(true);
        but21.setEnabled(true);
        but22.setEnabled(true);
        but23.setEnabled(true);
        but24.setEnabled(true);
        but25.setEnabled(true);
        but26.setEnabled(true);
        but27.setEnabled(true);
        but28.setEnabled(true);
        but29.setEnabled(true);
        but30.setEnabled(true);
        but31.setEnabled(true);
        but32.setEnabled(true);
        but33.setEnabled(true);
        but34.setEnabled(true);
        but35.setEnabled(true);
    }
    @Override
    public void disable(){
        jTextField2.setEnabled(false);
        jRadioButton2.setEnabled(true);
        jRadioButton1.setEnabled(false);
        but1.setEnabled(false);
        but2.setEnabled(false);
        but3.setEnabled(false);
        but4.setEnabled(false);
        but5.setEnabled(false);
        but6.setEnabled(false);
        but7.setEnabled(false);
        but8.setEnabled(false);
        but9.setEnabled(false);
        but10.setEnabled(false);
        but11.setEnabled(false);
        but12.setEnabled(false);
        but13.setEnabled(false);
        but14.setEnabled(false);
        but15.setEnabled(false);
        but16.setEnabled(false);
        but17.setEnabled(false);
        but18.setEnabled(false);
        but19.setEnabled(false);
        but20.setEnabled(false);
        but21.setEnabled(false);
        but22.setEnabled(false);
        but23.setEnabled(false);
        but24.setEnabled(false);
        but25.setEnabled(false);
        but26.setEnabled(false);
        but27.setEnabled(false);
        but28.setEnabled(false);
        but29.setEnabled(false);
        but30.setEnabled(false);
        but31.setEnabled(false);
        but32.setEnabled(false);
        but33.setEnabled(false);
        but34.setEnabled(false);
        but35.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        but1 = new javax.swing.JButton();
        but6 = new javax.swing.JButton();
        but16 = new javax.swing.JButton();
        but21 = new javax.swing.JButton();
        but26 = new javax.swing.JButton();
        but31 = new javax.swing.JButton();
        but13 = new javax.swing.JButton();
        but11 = new javax.swing.JButton();
        but2 = new javax.swing.JButton();
        but17 = new javax.swing.JButton();
        but22 = new javax.swing.JButton();
        but27 = new javax.swing.JButton();
        but32 = new javax.swing.JButton();
        but8 = new javax.swing.JButton();
        but12 = new javax.swing.JButton();
        but3 = new javax.swing.JButton();
        but18 = new javax.swing.JButton();
        but23 = new javax.swing.JButton();
        but28 = new javax.swing.JButton();
        but33 = new javax.swing.JButton();
        but9 = new javax.swing.JButton();
        but7 = new javax.swing.JButton();
        but4 = new javax.swing.JButton();
        but19 = new javax.swing.JButton();
        but24 = new javax.swing.JButton();
        but29 = new javax.swing.JButton();
        but34 = new javax.swing.JButton();
        but10 = new javax.swing.JButton();
        but15 = new javax.swing.JButton();
        but5 = new javax.swing.JButton();
        but20 = new javax.swing.JButton();
        but25 = new javax.swing.JButton();
        but30 = new javax.swing.JButton();
        but35 = new javax.swing.JButton();
        but14 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Cambria", 2, 24)); // NOI18N
        jLabel1.setText("         My Scientific Calculator");

        but1.setBackground(new java.awt.Color(0, 102, 102));
        but1.setText("R");
        but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1ActionPerformed(evt);
            }
        });

        but6.setBackground(new java.awt.Color(0, 102, 102));
        but6.setText("1/x");
        but6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but6ActionPerformed(evt);
            }
        });

        but16.setBackground(new java.awt.Color(0, 102, 102));
        but16.setText("%");
        but16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but16ActionPerformed(evt);
            }
        });

        but21.setBackground(new java.awt.Color(0, 102, 102));
        but21.setText("x^y");
        but21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but21ActionPerformed(evt);
            }
        });

        but26.setBackground(new java.awt.Color(0, 102, 102));
        but26.setText("10^x");
        but26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but26ActionPerformed(evt);
            }
        });

        but31.setBackground(new java.awt.Color(0, 102, 102));
        but31.setText("log");
        but31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but31ActionPerformed(evt);
            }
        });

        but13.setBackground(new java.awt.Color(0, 102, 102));
        but13.setText("Clr");
        but13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but13ActionPerformed(evt);
            }
        });

        but11.setBackground(new java.awt.Color(0, 102, 102));
        but11.setText("x^2");
        but11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but11ActionPerformed(evt);
            }
        });

        but2.setBackground(new java.awt.Color(0, 102, 102));
        but2.setForeground(new java.awt.Color(51, 51, 51));
        but2.setText("e^x");
        but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2ActionPerformed(evt);
            }
        });

        but17.setBackground(new java.awt.Color(0, 102, 102));
        but17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but17.setText("7");
        but17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but17ActionPerformed(evt);
            }
        });

        but22.setBackground(new java.awt.Color(0, 102, 102));
        but22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but22.setText("4");
        but22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but22ActionPerformed(evt);
            }
        });

        but27.setBackground(new java.awt.Color(0, 102, 102));
        but27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but27.setText("1");
        but27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but27ActionPerformed(evt);
            }
        });

        but32.setBackground(new java.awt.Color(0, 102, 102));
        but32.setText("+/-");
        but32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but32ActionPerformed(evt);
            }
        });

        but8.setBackground(new java.awt.Color(0, 102, 102));
        but8.setText("Sinh");
        but8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but8ActionPerformed(evt);
            }
        });

        but12.setBackground(new java.awt.Color(0, 102, 102));
        but12.setText("x^3");
        but12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but12ActionPerformed(evt);
            }
        });

        but3.setBackground(new java.awt.Color(0, 102, 102));
        but3.setText("Sin");
        but3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but3ActionPerformed(evt);
            }
        });

        but18.setBackground(new java.awt.Color(0, 102, 102));
        but18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but18.setText("8");
        but18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but18ActionPerformed(evt);
            }
        });

        but23.setBackground(new java.awt.Color(0, 102, 102));
        but23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but23.setText("5");
        but23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but23ActionPerformed(evt);
            }
        });

        but28.setBackground(new java.awt.Color(0, 102, 102));
        but28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but28.setText("2");
        but28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but28ActionPerformed(evt);
            }
        });

        but33.setBackground(new java.awt.Color(0, 102, 102));
        but33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but33.setText("0");
        but33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but33ActionPerformed(evt);
            }
        });

        but9.setBackground(new java.awt.Color(0, 102, 102));
        but9.setText("Cosh");
        but9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but9ActionPerformed(evt);
            }
        });

        but7.setBackground(new java.awt.Color(0, 102, 102));
        but7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        but7.setText("n!");
        but7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but7ActionPerformed(evt);
            }
        });

        but4.setBackground(new java.awt.Color(0, 102, 102));
        but4.setText("Cos");
        but4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but4ActionPerformed(evt);
            }
        });

        but19.setBackground(new java.awt.Color(0, 102, 102));
        but19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but19.setText("9");
        but19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but19ActionPerformed(evt);
            }
        });

        but24.setBackground(new java.awt.Color(0, 102, 102));
        but24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but24.setText("6");
        but24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but24ActionPerformed(evt);
            }
        });

        but29.setBackground(new java.awt.Color(0, 102, 102));
        but29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but29.setText("3");
        but29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but29ActionPerformed(evt);
            }
        });

        but34.setBackground(new java.awt.Color(0, 102, 102));
        but34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but34.setText(".");
        but34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but34ActionPerformed(evt);
            }
        });

        but10.setBackground(new java.awt.Color(0, 102, 102));
        but10.setText("Tanh");
        but10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but10ActionPerformed(evt);
            }
        });

        but15.setBackground(new java.awt.Color(0, 102, 102));
        but15.setText("/");
        but15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but15ActionPerformed(evt);
            }
        });

        but5.setBackground(new java.awt.Color(0, 102, 102));
        but5.setText("Tan");
        but5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but5ActionPerformed(evt);
            }
        });

        but20.setBackground(new java.awt.Color(0, 102, 102));
        but20.setText("*");
        but20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but20ActionPerformed(evt);
            }
        });

        but25.setBackground(new java.awt.Color(0, 102, 102));
        but25.setText("-");
        but25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but25ActionPerformed(evt);
            }
        });

        but30.setBackground(new java.awt.Color(0, 102, 102));
        but30.setText("+");
        but30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but30ActionPerformed(evt);
            }
        });

        but35.setBackground(new java.awt.Color(0, 102, 102));
        but35.setText("=");
        but35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but35ActionPerformed(evt);
            }
        });

        but14.setBackground(new java.awt.Color(0, 102, 102));
        but14.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        but14.setText("B");
        but14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but14ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setText("Off");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton2.setText("On");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but21, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but26, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but31, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but17, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but22, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but27, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but32, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(but3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but23, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but28, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but33, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(but4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but24, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but29, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but34, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(but13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but20, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but25, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but30, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but35, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but21, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but22, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but23, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but24, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but25, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but26, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but27, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but28, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but29, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but30, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but31, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but32, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but33, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but34, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but35, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(but8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but19, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but20, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1ActionPerformed
        // TODO add your handling code here:
        double t = Math.sqrt(Double.parseDouble(jTextField2.getText()));
        jTextField2.setText("");
        jTextField2.setText(jTextField2.getText() + t);
    }//GEN-LAST:event_but1ActionPerformed

    private void but6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but6ActionPerformed
        // TODO add your handling code here:
        double t = 1/(Double.parseDouble(jTextField2.getText()));
        jTextField2.setText("");
        jTextField2.setText(jTextField2.getText() + t);
    }//GEN-LAST:event_but6ActionPerformed

    private void but16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but16ActionPerformed
        // TODO add your handling code here:
        first = Double.parseDouble(jTextField2.getText());
        jTextField2.setText("");
        Operation="%";
    }//GEN-LAST:event_but16ActionPerformed

    private void but21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but21ActionPerformed
        // TODO add your handling code here:
        first = Double.parseDouble(jTextField2.getText());
        jTextField2.setText("");
        Operation="x^y";
        
    }//GEN-LAST:event_but21ActionPerformed

    private void but26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but26ActionPerformed
        // TODO add your handling code here:
        double t =Double.parseDouble(jTextField2.getText());
        t=Math.pow(10, t);
        jTextField2.setText("");
        jTextField2.setText(jTextField2.getText() + t);
    }//GEN-LAST:event_but26ActionPerformed

    private void but31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but31ActionPerformed
        // TODO add your handling code here:
        double t = Math.log(Double.parseDouble(jTextField2.getText()));
        jTextField2.setText("");
        jTextField2.setText(jTextField2.getText() + t);
    }//GEN-LAST:event_but31ActionPerformed

    private void but13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but13ActionPerformed

        jTextField2.setText( "");
    }//GEN-LAST:event_but13ActionPerformed

    private void but11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but11ActionPerformed
        // TODO add your handling code here:
        double t =Double.parseDouble(jTextField2.getText());
        t=t*t;
        jTextField2.setText("");
        jTextField2.setText(jTextField2.getText() + t);
        
    }//GEN-LAST:event_but11ActionPerformed

    private void but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2ActionPerformed
        // TODO add your handling code here:
        double t = Math.exp(Double.parseDouble(jTextField2.getText()));
        jTextField2.setText("");
        jTextField2.setText(jTextField2.getText() + t);
    }//GEN-LAST:event_but2ActionPerformed

    private void but17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but17ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(jTextField2.getText() + "7");
    }//GEN-LAST:event_but17ActionPerformed

    private void but22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but22ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(jTextField2.getText() + "4");
    }//GEN-LAST:event_but22ActionPerformed

    private void but27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but27ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(jTextField2.getText() + "1");
    }//GEN-LAST:event_but27ActionPerformed

    private void but32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but32ActionPerformed
        // TODO add your handling code here:
        double t = Double.parseDouble(String.valueOf(jTextField2.getText()));
        t=t*(-1);
        jTextField2.setText(String.valueOf(t));
        
    }//GEN-LAST:event_but32ActionPerformed

    private void but8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but8ActionPerformed
        // TODO add your handling code here:
        double t = Math.sinh(Double.parseDouble(jTextField2.getText()));
        jTextField2.setText("");
        jTextField2.setText(jTextField2.getText() + t);
        
    }//GEN-LAST:event_but8ActionPerformed

    private void but12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but12ActionPerformed
        // TODO add your handling code here:
        double t =Double.parseDouble(jTextField2.getText());
        t=t*t*t;
        jTextField2.setText("");
        jTextField2.setText(jTextField2.getText() + t);
    }//GEN-LAST:event_but12ActionPerformed

    private void but3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but3ActionPerformed
        // TODO add your handling code here:
        double t = Math.sin(Double.parseDouble(jTextField2.getText()));
        jTextField2.setText("");
        jTextField2.setText(jTextField2.getText() + t);
    }//GEN-LAST:event_but3ActionPerformed

    private void but18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but18ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(jTextField2.getText() + "8");
    }//GEN-LAST:event_but18ActionPerformed

    private void but23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but23ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(jTextField2.getText() + "5");
    }//GEN-LAST:event_but23ActionPerformed

    private void but28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but28ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(jTextField2.getText() + "2");
    }//GEN-LAST:event_but28ActionPerformed

    private void but33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but33ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(jTextField2.getText() + "0");
    }//GEN-LAST:event_but33ActionPerformed

    private void but9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but9ActionPerformed
        // TODO add your handling code here:
        double t = Math.cosh(Double.parseDouble(jTextField2.getText()));
        jTextField2.setText("");
        jTextField2.setText(jTextField2.getText() + t);
    }//GEN-LAST:event_but9ActionPerformed

    private void but7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but7ActionPerformed
        // TODO add your handling code here:
        int n =Integer.parseInt(jTextField2.getText());
        int fact=1;
        while(n!=0){
            fact=fact*n;
            n--;
        }
        jTextField2.setText("");
        jTextField2.setText(jTextField2.getText() + fact);
    }//GEN-LAST:event_but7ActionPerformed

    private void but4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but4ActionPerformed
        // TODO add your handling code here:
        double t = Math.cos(Double.parseDouble(jTextField2.getText()));
        jTextField2.setText("");
        jTextField2.setText(jTextField2.getText() + t);
    }//GEN-LAST:event_but4ActionPerformed

    private void but19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but19ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(jTextField2.getText() + "9");
    }//GEN-LAST:event_but19ActionPerformed

    private void but24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but24ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(jTextField2.getText() + "6");
    }//GEN-LAST:event_but24ActionPerformed

    private void but29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but29ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(jTextField2.getText() + "3");
    }//GEN-LAST:event_but29ActionPerformed

    private void but34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but34ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(jTextField2.getText() + ".");
    }//GEN-LAST:event_but34ActionPerformed

    private void but10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but10ActionPerformed
        // TODO add your handling code here:
        double t = Math.tanh(Double.parseDouble(jTextField2.getText()));
        jTextField2.setText("");
        jTextField2.setText(jTextField2.getText() + t);
    }//GEN-LAST:event_but10ActionPerformed

    private void but15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but15ActionPerformed
        // TODO add your handling code here:
        first = Double.parseDouble(jTextField2.getText());
        jTextField2.setText("");
        Operation="/";
    }//GEN-LAST:event_but15ActionPerformed

    private void but5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but5ActionPerformed
        // TODO add your handling code here:
        double t = Math.tan(Double.parseDouble(jTextField2.getText()));
        jTextField2.setText("");
        jTextField2.setText(jTextField2.getText() + t);
    }//GEN-LAST:event_but5ActionPerformed

    private void but20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but20ActionPerformed
        // TODO add your handling code here:
        first = Double.parseDouble(jTextField2.getText());
        jTextField2.setText("");
        Operation="*";
    }//GEN-LAST:event_but20ActionPerformed

    private void but25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but25ActionPerformed
        // TODO add your handling code here:
        first = Double.parseDouble(jTextField2.getText());
        jTextField2.setText("");
        Operation="-";
    }//GEN-LAST:event_but25ActionPerformed

    private void but30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but30ActionPerformed
        // TODO add your handling code here:
        first = Double.parseDouble(jTextField2.getText());
        jTextField2.setText("");
        Operation="+";
    }//GEN-LAST:event_but30ActionPerformed

    private void but35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but35ActionPerformed
        // TODO add your handling code here:
        second=Double.parseDouble(jTextField2.getText());
        if(null != Operation)switch (Operation) {
            case "+" -> {
                result = first+second;
                answer=String.format("%.2f", result);
                jTextField2.setText(answer);
            }
            case "-" -> {
                result = first-second;
                answer=String.format("%.2f", result);
                jTextField2.setText(answer);
            }
            case "*" -> {
                result = first*second;
                answer=String.format("%.2f", result);
                jTextField2.setText(answer);
            }
            case "/" -> {
                result = first/second;
                answer=String.format("%.2f", result);
                jTextField2.setText(answer);
            }
            case "%" -> {
                result = first%second;
                answer=String.format("%.1f", result);
                jTextField2.setText(answer);
            }
            case "x^y" -> {
                result = Math.pow(first,second);
                answer=String.format("%.2f", result);
                jTextField2.setText(answer);
            }
            default -> {
            }
        }
        
    }//GEN-LAST:event_but35ActionPerformed

    private void but14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but14ActionPerformed
        // TODO add your handling code here:
        String backspace = null;
        if(jTextField2.getText().length() > 0){
            StringBuilder sc = new StringBuilder(jTextField2.getText());
            sc.deleteCharAt(jTextField2.getText().length() - 1);
            backspace = sc.toString();
            jTextField2.setText(backspace);
        }
        
        
    }//GEN-LAST:event_but14ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        enable();
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        disable();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but1;
    private javax.swing.JButton but10;
    private javax.swing.JButton but11;
    private javax.swing.JButton but12;
    private javax.swing.JButton but13;
    private javax.swing.JButton but14;
    private javax.swing.JButton but15;
    private javax.swing.JButton but16;
    private javax.swing.JButton but17;
    private javax.swing.JButton but18;
    private javax.swing.JButton but19;
    private javax.swing.JButton but2;
    private javax.swing.JButton but20;
    private javax.swing.JButton but21;
    private javax.swing.JButton but22;
    private javax.swing.JButton but23;
    private javax.swing.JButton but24;
    private javax.swing.JButton but25;
    private javax.swing.JButton but26;
    private javax.swing.JButton but27;
    private javax.swing.JButton but28;
    private javax.swing.JButton but29;
    private javax.swing.JButton but3;
    private javax.swing.JButton but30;
    private javax.swing.JButton but31;
    private javax.swing.JButton but32;
    private javax.swing.JButton but33;
    private javax.swing.JButton but34;
    private javax.swing.JButton but35;
    private javax.swing.JButton but4;
    private javax.swing.JButton but5;
    private javax.swing.JButton but6;
    private javax.swing.JButton but7;
    private javax.swing.JButton but8;
    private javax.swing.JButton but9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
